//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Mio;

public class Position implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public int busId;

    public int lineId;

    public int stopId;

    public long odometer;

    public double latitude;

    public double longitude;

    public double speedKmh;

    public String timestamp;

    public Position()
    {
        this.timestamp = "";
    }

    public Position(int busId, int lineId, int stopId, long odometer, double latitude, double longitude, double speedKmh, String timestamp)
    {
        this.busId = busId;
        this.lineId = lineId;
        this.stopId = stopId;
        this.odometer = odometer;
        this.latitude = latitude;
        this.longitude = longitude;
        this.speedKmh = speedKmh;
        this.timestamp = timestamp;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Position r = null;
        if(rhs instanceof Position)
        {
            r = (Position)rhs;
        }

        if(r != null)
        {
            if(this.busId != r.busId)
            {
                return false;
            }
            if(this.lineId != r.lineId)
            {
                return false;
            }
            if(this.stopId != r.stopId)
            {
                return false;
            }
            if(this.odometer != r.odometer)
            {
                return false;
            }
            if(this.latitude != r.latitude)
            {
                return false;
            }
            if(this.longitude != r.longitude)
            {
                return false;
            }
            if(this.speedKmh != r.speedKmh)
            {
                return false;
            }
            if(this.timestamp != r.timestamp)
            {
                if(this.timestamp == null || r.timestamp == null || !this.timestamp.equals(r.timestamp))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Mio::Position");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, busId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, stopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, odometer);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, latitude);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, longitude);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, speedKmh);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        return h_;
    }

    public Position clone()
    {
        Position c = null;
        try
        {
            c = (Position)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.busId);
        ostr.writeInt(this.lineId);
        ostr.writeInt(this.stopId);
        ostr.writeLong(this.odometer);
        ostr.writeDouble(this.latitude);
        ostr.writeDouble(this.longitude);
        ostr.writeDouble(this.speedKmh);
        ostr.writeString(this.timestamp);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.busId = istr.readInt();
        this.lineId = istr.readInt();
        this.stopId = istr.readInt();
        this.odometer = istr.readLong();
        this.latitude = istr.readDouble();
        this.longitude = istr.readDouble();
        this.speedKmh = istr.readDouble();
        this.timestamp = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Position v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Position ice_read(com.zeroc.Ice.InputStream istr)
    {
        Position v = new Position();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Position> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Position v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Position> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Position.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Position _nullMarshalValue = new Position();

    /** @hidden */
    public static final long serialVersionUID = -250940515L;
}
