//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Mio;

public class Route implements java.lang.Cloneable,
                              java.io.Serializable
{
    public int lineId;

    public String shortName;

    public String description;

    public Route()
    {
        this.shortName = "";
        this.description = "";
    }

    public Route(int lineId, String shortName, String description)
    {
        this.lineId = lineId;
        this.shortName = shortName;
        this.description = description;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Route r = null;
        if(rhs instanceof Route)
        {
            r = (Route)rhs;
        }

        if(r != null)
        {
            if(this.lineId != r.lineId)
            {
                return false;
            }
            if(this.shortName != r.shortName)
            {
                if(this.shortName == null || r.shortName == null || !this.shortName.equals(r.shortName))
                {
                    return false;
                }
            }
            if(this.description != r.description)
            {
                if(this.description == null || r.description == null || !this.description.equals(r.description))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Mio::Route");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, shortName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, description);
        return h_;
    }

    public Route clone()
    {
        Route c = null;
        try
        {
            c = (Route)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.lineId);
        ostr.writeString(this.shortName);
        ostr.writeString(this.description);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.lineId = istr.readInt();
        this.shortName = istr.readString();
        this.description = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Route v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Route ice_read(com.zeroc.Ice.InputStream istr)
    {
        Route v = new Route();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Route> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Route v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Route> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Route.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Route _nullMarshalValue = new Route();

    /** @hidden */
    public static final long serialVersionUID = 144083758L;
}
