//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Mio;

public class RouteMapData implements java.lang.Cloneable,
                                     java.io.Serializable
{
    public Route route;

    public Station[] stations;

    public RoutePoint[] baseGeometry;

    public RouteMapData()
    {
        this.route = new Route();
    }

    public RouteMapData(Route route, Station[] stations, RoutePoint[] baseGeometry)
    {
        this.route = route;
        this.stations = stations;
        this.baseGeometry = baseGeometry;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        RouteMapData r = null;
        if(rhs instanceof RouteMapData)
        {
            r = (RouteMapData)rhs;
        }

        if(r != null)
        {
            if(this.route != r.route)
            {
                if(this.route == null || r.route == null || !this.route.equals(r.route))
                {
                    return false;
                }
            }
            if(!java.util.Arrays.equals(this.stations, r.stations))
            {
                return false;
            }
            if(!java.util.Arrays.equals(this.baseGeometry, r.baseGeometry))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Mio::RouteMapData");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, route);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, stations);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, baseGeometry);
        return h_;
    }

    public RouteMapData clone()
    {
        RouteMapData c = null;
        try
        {
            c = (RouteMapData)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        Route.ice_write(ostr, this.route);
        StationSeqHelper.write(ostr, this.stations);
        RoutePointSeqHelper.write(ostr, this.baseGeometry);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.route = Route.ice_read(istr);
        this.stations = StationSeqHelper.read(istr);
        this.baseGeometry = RoutePointSeqHelper.read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, RouteMapData v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public RouteMapData ice_read(com.zeroc.Ice.InputStream istr)
    {
        RouteMapData v = new RouteMapData();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<RouteMapData> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, RouteMapData v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<RouteMapData> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(RouteMapData.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final RouteMapData _nullMarshalValue = new RouteMapData();

    /** @hidden */
    public static final long serialVersionUID = 348632845L;
}
