//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Mio;

public class RoutePoint implements java.lang.Cloneable,
                                   java.io.Serializable
{
    public int lineId;

    public double latitude;

    public double longitude;

    public int order;

    public RoutePoint()
    {
    }

    public RoutePoint(int lineId, double latitude, double longitude, int order)
    {
        this.lineId = lineId;
        this.latitude = latitude;
        this.longitude = longitude;
        this.order = order;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        RoutePoint r = null;
        if(rhs instanceof RoutePoint)
        {
            r = (RoutePoint)rhs;
        }

        if(r != null)
        {
            if(this.lineId != r.lineId)
            {
                return false;
            }
            if(this.latitude != r.latitude)
            {
                return false;
            }
            if(this.longitude != r.longitude)
            {
                return false;
            }
            if(this.order != r.order)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Mio::RoutePoint");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, latitude);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, longitude);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, order);
        return h_;
    }

    public RoutePoint clone()
    {
        RoutePoint c = null;
        try
        {
            c = (RoutePoint)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.lineId);
        ostr.writeDouble(this.latitude);
        ostr.writeDouble(this.longitude);
        ostr.writeInt(this.order);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.lineId = istr.readInt();
        this.latitude = istr.readDouble();
        this.longitude = istr.readDouble();
        this.order = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, RoutePoint v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public RoutePoint ice_read(com.zeroc.Ice.InputStream istr)
    {
        RoutePoint v = new RoutePoint();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<RoutePoint> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, RoutePoint v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(24);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<RoutePoint> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(RoutePoint.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final RoutePoint _nullMarshalValue = new RoutePoint();

    /** @hidden */
    public static final long serialVersionUID = 1691221771L;
}
