//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Mio;

/**
 * Helper class for marshaling/unmarshaling RoutePointSeq.
 **/
public final class RoutePointSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, RoutePoint[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                RoutePoint.ice_write(ostr, v[i0]);
            }
        }
    }

    public static RoutePoint[] read(com.zeroc.Ice.InputStream istr)
    {
        final RoutePoint[] v;
        final int len0 = istr.readAndCheckSeqSize(24);
        v = new RoutePoint[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = RoutePoint.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<RoutePoint[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, RoutePoint[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            final int optSize = v == null ? 0 : v.length;
            ostr.writeSize(optSize > 254 ? optSize * 24 + 5 : optSize * 24 + 1);
            RoutePointSeqHelper.write(ostr, v);
        }
    }

    public static java.util.Optional<RoutePoint[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            RoutePoint[] v;
            v = RoutePointSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
