//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Mio;

/**
 * Helper class for marshaling/unmarshaling StationSeq.
 **/
public final class StationSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, Station[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                Station.ice_write(ostr, v[i0]);
            }
        }
    }

    public static Station[] read(com.zeroc.Ice.InputStream istr)
    {
        final Station[] v;
        final int len0 = istr.readAndCheckSeqSize(26);
        v = new Station[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = Station.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Station[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, Station[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            StationSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<Station[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            Station[] v;
            v = StationSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
