//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Mio;

public class Station implements java.lang.Cloneable,
                                java.io.Serializable
{
    public int id;

    public int lineId;

    public String name;

    public double latitude;

    public double longitude;

    public String kind;

    public Station()
    {
        this.name = "";
        this.kind = "";
    }

    public Station(int id, int lineId, String name, double latitude, double longitude, String kind)
    {
        this.id = id;
        this.lineId = lineId;
        this.name = name;
        this.latitude = latitude;
        this.longitude = longitude;
        this.kind = kind;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Station r = null;
        if(rhs instanceof Station)
        {
            r = (Station)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                return false;
            }
            if(this.lineId != r.lineId)
            {
                return false;
            }
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }
            if(this.latitude != r.latitude)
            {
                return false;
            }
            if(this.longitude != r.longitude)
            {
                return false;
            }
            if(this.kind != r.kind)
            {
                if(this.kind == null || r.kind == null || !this.kind.equals(r.kind))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Mio::Station");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, latitude);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, longitude);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, kind);
        return h_;
    }

    public Station clone()
    {
        Station c = null;
        try
        {
            c = (Station)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.id);
        ostr.writeInt(this.lineId);
        ostr.writeString(this.name);
        ostr.writeDouble(this.latitude);
        ostr.writeDouble(this.longitude);
        ostr.writeString(this.kind);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readInt();
        this.lineId = istr.readInt();
        this.name = istr.readString();
        this.latitude = istr.readDouble();
        this.longitude = istr.readDouble();
        this.kind = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Station v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Station ice_read(com.zeroc.Ice.InputStream istr)
    {
        Station v = new Station();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Station> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Station v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Station> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Station.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Station _nullMarshalValue = new Station();

    /** @hidden */
    public static final long serialVersionUID = -1749228792L;
}
